Booth/dev
SanDiegoCountySheriff/CSSA-CCW pull request #4
Opened 2022-09-20 20:39 UTC by jeremiahbooth-insight

Created the starting veux store for the UI and started laying out the stepper form

2022-09-20 21:06 UTC, sgaddameedi-insight requested changes
Apart from above comments, LGTM.

2022-09-20 21:06 UTC, sgaddameedi-insight commented on UI/libs/shared/ui/src/lib/store/mutations/DOBMutations.js
> +export const GET_DOB = 'GET_DOB';
We probably want to keep the (state, actions, mutations etc in one file instead of going by a particular feature’s state and mutations inside two diff folders. Think about it like a feature, which will help maintain the Nx philosophy and would be easier to migrate or make it buildable/publishable library in future if we need to.

2022-09-20 21:06 UTC, sgaddameedi-insight commented on UI/libs/shared/ui/src/lib/store/mutations/DOBMutations.js
> +export const GET_DOB = 'GET_DOB';
I see these are just constants, so maybe we can move these into modules and delete the mutations folder?

2022-09-20 21:06 UTC, sgaddameedi-insight commented on UI/libs/shared/ui/src/lib/store/index.ts
> +export const store = new Vuex.Store({
This would help avoid bleeding any unnecessary modules into each other’s store.

2022-09-20 21:08 UTC, sgaddameedi-insight commented
Also can u please rebase from main or use git script (which does automatically). Thanks!

2022-09-20 21:18 UTC, sgaddameedi-insight requested changes

2022-09-20 21:18 UTC, sgaddameedi-insight commented on UI/libs/core-public/src/lib/views/FormView.vue
> +<script>
Use lang=“ts” on all the script tags for vue files.

2022-09-21 14:12 UTC, jeremiahbooth-insight commented on UI/libs/shared/ui/src/lib/store/mutations/DOBMutations.js
> +export const GET_DOB = 'GET_DOB';
I can if you want. The idea was to avoid magic strings without polluting the modules

2022-09-21 14:14 UTC, jeremiahbooth-insight commented
And I did use the git scripts... is there something that doesn't look right?

2022-09-21 15:33 UTC, jeremiahbooth-insight commented
Ok Notes on the changes 
 - Figured out a way to avoid the circular dependancies. The store in the shared ui is the main one that gets imported into each apps store then the app adds the modules that it needs.

2022-09-21 15:50 UTC, sgaddameedi-insight commented
LGTM Thanks!

2022-09-21 15:51 UTC, merged