Feat: add validation for reschedule and cancel  button
SanDiegoCountySheriff/CSSA-CCW pull request #414
Opened 2023-06-22 19:12 UTC by SDSheriffShawnVahle

Also add loading indicators

# Description

Fixed validation rules for reschedule and cancel button on application detail

Fixes # issue ticket number and link
AB#2634

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [X] API unit tests

2023-06-22 21:21 UTC, nwolfosh approved these changes

2023-06-23 13:58 UTC, jacobkellas commented on UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
> +    applicationStore.completeApplication.application.status !== 4 &&
One thing we're going to want to avoid in the future is "magic numbers"  If you come back to this code in a year it's going to be hard to remember what status 6 is.

In the constants file we should create key/value pairs of applications statuses.  That way this will read:

application.status !== APPLICATION_STATUSES.withdrawn or whatever, and that will equal 6 or whatever the status is.

2023-06-23 14:07 UTC, jacobkellas requested changes

2023-06-23 14:07 UTC, jacobkellas commented on UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
> -    applicationStore.completeApplication.application.status !== 6
In fact let's go ahead and make this change.  Let me know if you have questions.

2023-06-23 14:16 UTC, SDSheriffShawnVahle commented on UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
> -    applicationStore.completeApplication.application.status !== 6
Agreed. Already looking into it.

2023-06-23 16:37 UTC, SDSheriffShawnVahle commented on UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
> +    applicationStore.completeApplication.application.status !== 4 &&
Done.

2023-06-23 16:37 UTC, SDSheriffShawnVahle commented on UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
> -    applicationStore.completeApplication.application.status !== 6
Done.

2023-06-23 16:39 UTC, jacobkellas approved these changes
@SDSheriffShawnVahle test after it builds to dev and make sure there aren't any regressions on the details pages for admin and public

2023-06-23 16:40 UTC, merged