Booth/dev
SanDiegoCountySheriff/CSSA-CCW pull request #5
Opened 2022-09-21 19:59 UTC by jeremiahbooth-insight

Created step two of the form.
 - updated validation of the forms
 - created a error alert for the forms

2022-09-21 20:41 UTC, sgaddameedi-insight requested changes

2022-09-21 20:41 UTC, sgaddameedi-insight commented on UI/libs/shared/ui/src/lib/components/form-stepper/form-steps/FormStepOne.vue
> +import { addPersonalInfoAction } from '@shared-ui/helpers/storeHelpers/personalInfoActions';
Possible to add an index to store helpers so its easy to get multiple helpers in a single import?

ex:
`import { helper1, helper2 } from ‘@shared-ui/helpers/storeHelper’;
`

2022-09-21 20:56 UTC, jeremiahbooth-insight commented on UI/libs/shared/ui/src/lib/components/form-stepper/form-steps/FormStepOne.vue
> +import { addPersonalInfoAction } from '@shared-ui/helpers/storeHelpers/personalInfoActions';
Soon they will have the one for get, add, update and delete in the same export. Or did you mean you want multiple modules helper functions to export from the same file. 

ie. 
personalInfo and alias combine into one file... instead of having their own?

2022-09-21 21:31 UTC, sgaddameedi-insight requested changes

2022-09-21 21:31 UTC, sgaddameedi-insight commented on UI/libs/shared/ui/src/lib/validators/form-validators/formStepOneValidators.ts
> +    errors.push('Last name');
I want to try and explore if there is any simpler way for form handling and validations (similar to react-hook-form). Let me try run this approach when i return on friday. Feel free to add more changes if ur still working.

2022-09-21 21:40 UTC, jeremiahbooth-insight commented on UI/libs/shared/ui/src/lib/validators/form-validators/formStepOneValidators.ts
> +    errors.push('Last name');
yeah I want to at least make these cleaner and they will need more validation criteria than this too.

2022-09-22 05:45 UTC, sgaddameedi-insight requested changes

2022-09-22 05:45 UTC, sgaddameedi-insight commented on UI/libs/shared/ui/src/lib/helpers/storeHelpers/storeActions.ts
> +export async function addAliasesAction(aliases: Array<Alias>) {
You can do mapping like below instead and move it inside it’s own module file (and delete helpers). This will make easy to read and navigate code without going through multiple folder/files for a single feature like Alias.

```js
import { mapActions } from 'vuex';

  // ...
  methods: {
    ...mapActions([
      addAliasAction: 'addAlias'
      ])
  }
```

You can do same thing for getters (and mutations, not sure if we need to maintain a saperate folder for it) if needed. My intention is a single module file should have everything needed from a vuex perspective, so that we can decouple individual components/features without having to refactor the application structure in future.

2022-09-22 05:45 UTC, sgaddameedi-insight commented on UI/libs/shared/ui/src/lib/validators/form-validators/formStepOneValidators.ts
> +    errors.push('Last name');
Lets explore something which is flexible for form validations and also has in-built form generators so it can reduce our timeline for buliding “brandable” templates on admin layer.

2022-09-22 05:47 UTC, sgaddameedi-insight commented on UI/libs/shared/ui/src/lib/types/defualtTypes.ts
> +export type Alias = {
Nice 👌🏻

2022-09-22 05:53 UTC, sgaddameedi-insight requested changes

2022-09-22 05:53 UTC, sgaddameedi-insight commented on UI/libs/shared/ui/src/lib/components/form-stepper/form-steps/FormStepTwo.vue
> +<style scoped>
Use scss for all style tags. 

To-do: Ill see if i can enforce lang attribute and scss for script and style tags through eslint.

2022-09-22 13:23 UTC, jeremiahbooth-insight commented on UI/libs/shared/ui/src/lib/components/form-stepper/form-steps/FormStepTwo.vue
> +<style scoped>
ok sounds good

2022-09-23 00:02 UTC, sgaddameedi-insight commented on UI/libs/shared/ui/src/lib/validators/form-validators/formStepOneValidators.ts
> +    errors.push('Last name');
@jeremiahbooth-insight - All other comments are resolved, Thanks for addressing them. Tried the current approach for forms but would highly recommend a well-maintained form handling package because of heavy usage of inputs and validations for this project, we won't be able to maintain custom handling/validations for this level of inputs (compared to RIPA which is somewhat simple). Can u check out https://github.com/wearebraid/vue-formulate or anything you would like which will be flexible for our use case in both admin/public apps? 

Also, We will have to start building test cases and stories per component basis. (storybook, I don't expect us to write for every single component but at least we can get it into good shape so the CCW team can carry forward.

One last thing, Can you please check with @chawkins-insight - I see ADA color contrast issues with default form error messages both in RIPA and CCW. We should address it before it spreads everywhere.

What I would do before every PR is:
1. Check ADA through Axe dev tools extension and make sure we are not violating any major rules there.
2. Run units (no need to worry about e2e)

2022-09-23 19:57 UTC, closed without merging