Task/2860 modifiable signature
SanDiegoCountySheriff/CSSA-CCW pull request #770
Opened 2024-06-27 16:59 UTC by alyssamarce

# Description

Made applicant signatures modifiable from the Application Review page. If the applicant clicks on the 'Modify Signature' button, their previous signature will be deleted, and they will be directed to the Signature tab of their application to create a new one.

Fixes # issue ticket number and link

AB#2860 - https://dev.azure.com/dsd-sdsd/CSSA-CCW/_workitems/edit/2860/

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

- [ ] API unit tests
- [X] UI unit tests
- [X] Azure Cosmos DB emulator testing

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings or errors
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

2024-06-27 17:26 UTC, jacobkellas requested changes

2024-06-27 17:26 UTC, jacobkellas commented on UI/libs/core-admin/src/lib/components/header/Header.vue
> +<style lang="scss" scoped>
![image](https://github.com/SanDiegoCountySheriff/CSSA-CCW/assets/83732510/b88bcb96-5ee5-4e3b-bae8-1f31ffd68915)
Looks like some issues with the border on the signature pad

2024-06-27 17:26 UTC, jacobkellas commented on UI/libs/shared/ui/src/lib/components/containers/SignatureFormButtonContainer.vue
> +<template>
Do we need to create a new form button container for the last step?  What does this do differently from the original FormButtonContainer?

2024-06-27 17:26 UTC, jacobkellas commented on UI/libs/core-public/src/lib/components/form-stepper/form-steps/SignatureStep.vue
> +<style lang="scss" scoped>
Same issue as above with the outline

2024-06-27 17:26 UTC, jacobkellas commented on UI/libs/core-public/src/lib/components/form-stepper/form-steps/SignatureStep.vue
> +const isSignatureMinLength = computed(() => {
We can remove the unused code for now.  I like the idea of this feature, we can experiment with it later and make it really solid.

2024-06-27 17:26 UTC, jacobkellas commented on UI/libs/shared/ui/src/lib/components/info-sections/FileUploadInfoSection.vue
> +const loadingStates = reactive({
Doesn't look like these loading states are being used

2024-06-27 17:26 UTC, jacobkellas commented on UI/libs/shared/ui/src/lib/components/info-sections/FileUploadInfoSection.vue
> +          viewSignatureSection()
I think we can simplify this by just having a dialog pop up that allows users to modify the signature directly from the application detail view.  Routing to the form might be a bit confusing.

2024-06-27 17:26 UTC, jacobkellas commented on UI/libs/shared/ui/src/lib/components/info-sections/FileUploadInfoSection.vue
> +        deleteFile(file.name).then(() => {
I believe (I'd have to double check) that signature will just overwrite when you upload a new one so there may not be a need to delete it first.

2024-06-27 18:53 UTC, jacobkellas requested changes

2024-06-27 18:53 UTC, jacobkellas commented on UI/libs/core-admin/src/lib/components/header/Header.vue
> -      backgroundColor: 'rgba(255, 255, 255, 0)',
I believe this might have been for opacity, to set the background to transparent.  Let's double check this.

2024-07-12 17:08 UTC, nwolfosh requested changes

2024-07-12 17:08 UTC, nwolfosh commented on UI/libs/shared/ui/src/lib/components/dialogs/ModifySignatureDialog.vue
> +            @click="handleSaveSignature"
Make sure the dialog closes once they hit save

2024-07-12 17:08 UTC, nwolfosh commented on UI/libs/shared/ui/src/lib/components/dialogs/ModifySignatureDialog.vue
> +      Your signature was successfully modified. Please inform Licensing so your
This looks great, I think we can just keep it at "Your signature was successfully modified."

2024-07-12 17:08 UTC, nwolfosh commented on UI/libs/shared/ui/src/lib/components/info-sections/FileUploadInfoSection.vue
We can remove the ModifySignatureDialog and the rest of the logic from the file upload section. We want to allow people to upload the signature even if they don't have one.

2024-07-12 17:08 UTC, nwolfosh commented on UI/libs/shared/ui/src/lib/components/info-sections/SignatureInfoSection.vue
> +              v-if="state.signature"
Lets talk about when we should display this dialog. I think we're leaning towards always letting them modify it unless their permit has been delivered, canceled, withdrawn, etc.

2024-07-12 17:09 UTC, nwolfosh commented on UI/libs/shared/ui/src/lib/components/dialogs/ModifySignatureDialog.vue
> +    <v-btn
The second button on line 17 specifically

2024-07-16 20:22 UTC, alyssamarce commented on UI/libs/shared/ui/src/lib/components/info-sections/SignatureInfoSection.vue
> +              v-if="state.signature"
I just spoke to Jake about this topic this morning. For now, he said we'll leave it in just to make it easier for users to get to an area to modify the signature. In the future, though, we might pivot to only having this be part of the file upload section.

2024-07-17 20:08 UTC, nwolfosh approved these changes

2024-07-17 20:12 UTC, merged